# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Build Go app
      run: |
          go mod tidy
          go build -o app .
      
    - name: Build Docker image
      run: |
          docker build -t my-go-app .
          
    - name: Stop and remove old container
      run: |
          docker stop my-go-app || true
          docker rm my-go-app || true

    - name: Deploy Docker container
      run: |
          docker run -d --name my-go-app -p 8080:8080 my-go-app
